name: CI/CD Workflow

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build:
    runs-on: self-hosted  # Change this to use your local runner
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Start Minikube
      run: |
        minikube status || minikube start
    
    - name: Build Docker image
      run: |
        eval $(minikube docker-env)
        docker build -t sagnik3788/wisecow:latest .
    
    - name: Load image to Minikube
      run: |
        minikube image load sagnik3788/wisecow:latest

  deploy:
    runs-on: self-hosted  # Use the same local runner
    needs: build  # Ensure the build job is complete before deploying
    
    steps:
    - name: Deploy to Minikube
      run: |
        kubectl set image deployment/wisecow wisecow=sagnik3788/wisecow:latest
        kubectl rollout status deployment/wisecow